In [1]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created :\n",a)

Array created :
 [[1 2 4]
 [5 8 7]]


In [2]:
#creating a 3*4 array with all zeros
b=np.zeros((3,4))
print("Array with all zeros:\n",b)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
#creating an array with random value
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.07701189 0.5283529 ]
 [0.60743305 0.11821822]]


In [4]:
#creating a sequence of integers from 0 to 30 with step of 5
import numpy as np
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [5]:
#Reshaping 3*4 array to 2*2*3 array
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr = arr.reshape(4,3)
print("\n original array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)


 original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [6]:
#flatten array
flarr = arr.flatten()
print("\n original array:\n",arr)
print("\n flatten array:\n",flarr)


 original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 flatten array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [7]:
import numpy as np
arr =np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
print("\n No.of dimensions:\n",arr.ndim)
print("\n Shape of array:\n",arr.shape)
print("\n size o0f array:\n",arr.size)
print("\n Array type:\n",arr.dtype)
newtype = arr.astype('f')
print("\n converted array element:\n",newtype)
print("\n converted array type:\n",newtype.dtype)


 No.of dimensions:
 2

 Shape of array:
 (3, 4)

 size o0f array:
 12

 Array type:
 int32

 converted array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

 converted array type:
 float32


In [8]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])
print(p[2,0:2])
print(p[2:,2:])
print(p[3:,3:])
print(p[:,1])
c=p.astype('f')
print(c)
e=p.astype('i')
print(e)

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[7 8]
[[ 9]
 [12]
 [15]]
[]
[ 2  5  8 11 14]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [9]:
#create a constant value array
c=np.full((3,3),6)
print("Array with all 6s;\n",c)

Array with all 6s;
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
